# Generated by Django 4.1 on 2022-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
