# Generated by Django 4.1 on 2022-08-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(db_index=True, help_text='This field is required', max_length=40),
        ),
    ]
